version: "3"

services:
   adguardhome:
     image: adguard/adguardhome
     container_name: adguardhome

     restart: always

     network_mode: host


     volumes:
       - /home/docker/adguardhome/work:/opt/adguardhome/work
       - /home/docker/adguardhome/conf:/opt/adguardhome/conf
       
    