version: '3.7'

services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/docker/dokuwiki/config:/config
    ports:
      - "443:443" # optional
    restart: always
