version: '3.1'

services:
  db:
    image: mariadb:latest
    container_name : mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - /home/docker/mariadb:/var/lib/mysql

      
volumes:
  mariadb: