version: '3.7'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - /home/docker/openldap/data/certificates:/container/service/slapd/assets/certs
      - /home/docker/openldap/data/slapd/database:/var/lib/ldap
      - /home/docker/openldap/data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=domain
      - LDAP_DOMAIN=domain.local
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_CONFIG_PASSWORD=config_pass


    networks:
      - openldap



networks:
  openldap:
    driver: bridge
